/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * item object
 */
export interface GetCharactersCharacterIdFittingsItem {
    /**
     * flag integer
     */
    flag: number;

    /**
     * quantity integer
     */
    quantity: number;

    /**
     * type_id integer
     */
    typeId: number;

}


