/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * service object
 */
export interface GetCorporationsCorporationIdStructuresService {
    /**
     * name string
     */
    name: string;

    /**
     * state string
     */
    state: GetCorporationsCorporationIdStructuresService.StateEnum;

}
export namespace GetCorporationsCorporationIdStructuresService {
    export type StateEnum = 'online' | 'offline' | 'cleanup';
}


