/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdContracts200Ok {
    /**
     * Who will accept the contract
     */
    acceptorId: number;

    /**
     * ID to whom the contract is assigned, can be corporation or character ID
     */
    assigneeId: number;

    /**
     * To whom the contract is available
     */
    availability: GetCharactersCharacterIdContracts200Ok.AvailabilityEnum;

    /**
     * Buyout price (for Auctions only)
     */
    buyout?: number;

    /**
     * Collateral price (for Couriers only)
     */
    collateral?: number;

    /**
     * contract_id integer
     */
    contractId: number;

    /**
     * Date of confirmation of contract
     */
    dateAccepted?: Date;

    /**
     * Date of completed of contract
     */
    dateCompleted?: Date;

    /**
     * Expiration date of the contract
     */
    dateExpired: Date;

    /**
     * Сreation date of the contract
     */
    dateIssued: Date;

    /**
     * Number of days to perform the contract
     */
    daysToComplete?: number;

    /**
     * End location ID (for Couriers contract)
     */
    endLocationId?: number;

    /**
     * true if the contract was issued on behalf of the issuer's corporation
     */
    forCorporation: boolean;

    /**
     * Character's corporation ID for the issuer
     */
    issuerCorporationId: number;

    /**
     * Character ID for the issuer
     */
    issuerId: number;

    /**
     * Price of contract (for ItemsExchange and Auctions)
     */
    price?: number;

    /**
     * Remuneration for contract (for Couriers only)
     */
    reward?: number;

    /**
     * Start location ID (for Couriers contract)
     */
    startLocationId?: number;

    /**
     * Status of the the contract
     */
    status: GetCharactersCharacterIdContracts200Ok.StatusEnum;

    /**
     * Title of the contract
     */
    title?: string;

    /**
     * Type of the contract
     */
    type: GetCharactersCharacterIdContracts200Ok.TypeEnum;

    /**
     * Volume of items in the contract
     */
    volume?: number;

}
export namespace GetCharactersCharacterIdContracts200Ok {
    export type AvailabilityEnum = 'public' | 'personal' | 'corporation' | 'alliance';
    export type StatusEnum = 'outstanding' | 'in_progress' | 'finished_issuer' | 'finished_contractor' | 'finished' | 'cancelled' | 'rejected' | 'failed' | 'deleted' | 'reversed';
    export type TypeEnum = 'unknown' | 'item_exchange' | 'auction' | 'courier' | 'loan';
}


