/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdFleetOk {
    /**
     * The character's current fleet ID
     */
    fleetId: number;

    /**
     * Member’s role in fleet
     */
    role: GetCharactersCharacterIdFleetOk.RoleEnum;

    /**
     * ID of the squad the member is in. If not applicable, will be set to -1
     */
    squadId: number;

    /**
     * ID of the wing the member is in. If not applicable, will be set to -1
     */
    wingId: number;

}
export namespace GetCharactersCharacterIdFleetOk {
    export type RoleEnum = 'fleet_commander' | 'squad_commander' | 'squad_member' | 'wing_commander';
}


