/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GetCharactersCharacterIdMailLabelsLabel } from './getCharactersCharacterIdMailLabelsLabel';


/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdMailLabelsOk {
    /**
     * labels array
     */
    labels?: Array<GetCharactersCharacterIdMailLabelsLabel>;

    /**
     * total_unread_count integer
     */
    totalUnreadCount?: number;

}


