/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * character_id and response of an attendee
 */
export interface GetCharactersCharacterIdCalendarEventIdAttendees200Ok {
    /**
     * character_id integer
     */
    characterId?: number;

    /**
     * event_response string
     */
    eventResponse?: GetCharactersCharacterIdCalendarEventIdAttendees200Ok.EventResponseEnum;

}
export namespace GetCharactersCharacterIdCalendarEventIdAttendees200Ok {
    export type EventResponseEnum = 'declined' | 'not_responded' | 'accepted' | 'tentative';
}


