/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GetCharactersCharacterIdMailRecipient } from './getCharactersCharacterIdMailRecipient';


/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdMail200Ok {
    /**
     * From whom the mail was sent
     */
    from?: number;

    /**
     * is_read boolean
     */
    isRead?: boolean;

    /**
     * labels array
     */
    labels?: Array<number>;

    /**
     * mail_id integer
     */
    mailId?: number;

    /**
     * Recipients of the mail
     */
    recipients?: Array<GetCharactersCharacterIdMailRecipient>;

    /**
     * Mail subject
     */
    subject?: string;

    /**
     * When the mail was sent
     */
    timestamp?: Date;

}


