/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * wallet transaction
 */
export interface GetCharactersCharacterIdWalletTransactions200Ok {
    /**
     * client_id integer
     */
    clientId: number;

    /**
     * Date and time of transaction
     */
    date: Date;

    /**
     * is_buy boolean
     */
    isBuy: boolean;

    /**
     * is_personal boolean
     */
    isPersonal: boolean;

    /**
     * journal_ref_id integer
     */
    journalRefId: number;

    /**
     * location_id integer
     */
    locationId: number;

    /**
     * quantity integer
     */
    quantity: number;

    /**
     * Unique transaction ID
     */
    transactionId: number;

    /**
     * type_id integer
     */
    typeId: number;

    /**
     * Amount paid per unit
     */
    unitPrice: number;

}


