/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdOk {
    /**
     * The character's alliance ID
     */
    allianceId?: number;

    /**
     * ancestry_id integer
     */
    ancestryId?: number;

    /**
     * Creation date of the character
     */
    birthday: Date;

    /**
     * bloodline_id integer
     */
    bloodlineId: number;

    /**
     * The character's corporation ID
     */
    corporationId: number;

    /**
     * description string
     */
    description?: string;

    /**
     * gender string
     */
    gender: GetCharactersCharacterIdOk.GenderEnum;

    /**
     * name string
     */
    name: string;

    /**
     * race_id integer
     */
    raceId: number;

    /**
     * security_status number
     */
    securityStatus?: number;

}
export namespace GetCharactersCharacterIdOk {
    export type GenderEnum = 'female' | 'male';
}


