/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * 200 ok object
 */
export interface GetCorporationsCorporationIdOk {
    /**
     * ID of the alliance that corporation is a member of, if any
     */
    allianceId?: number;

    /**
     * ceo_id integer
     */
    ceoId: number;

    /**
     * creator_id integer
     */
    creatorId: number;

    /**
     * date_founded string
     */
    dateFounded?: Date;

    /**
     * description string
     */
    description?: string;

    /**
     * faction_id integer
     */
    factionId?: number;

    /**
     * home_station_id integer
     */
    homeStationId?: number;

    /**
     * member_count integer
     */
    memberCount: number;

    /**
     * the full name of the corporation
     */
    name: string;

    /**
     * shares integer
     */
    shares?: number;

    /**
     * tax_rate number
     */
    taxRate: number;

    /**
     * the short name of the corporation
     */
    ticker: string;

    /**
     * url string
     */
    url?: string;

}


