/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * label object
 */
export interface GetCharactersCharacterIdMailLabelsLabel {
    /**
     * color string
     */
    color?: GetCharactersCharacterIdMailLabelsLabel.ColorEnum;

    /**
     * label_id integer
     */
    labelId?: number;

    /**
     * name string
     */
    name?: string;

    /**
     * unread_count integer
     */
    unreadCount?: number;

}
export namespace GetCharactersCharacterIdMailLabelsLabel {
    export type ColorEnum = '#0000fe' | '#006634' | '#0099ff' | '#00ff33' | '#01ffff' | '#349800' | '#660066' | '#666666' | '#999999' | '#99ffff' | '#9a0000' | '#ccff9a' | '#e6e6e6' | '#fe0000' | '#ff6600' | '#ffff01' | '#ffffcd' | '#ffffff';
}


