/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GetCorporationsCorporationIdBookmarksCoordinates } from './getCorporationsCorporationIdBookmarksCoordinates';
import { GetCorporationsCorporationIdBookmarksItem } from './getCorporationsCorporationIdBookmarksItem';


/**
 * 200 ok object
 */
export interface GetCorporationsCorporationIdBookmarks200Ok {
    /**
     * bookmark_id integer
     */
    bookmarkId: number;

    coordinates?: GetCorporationsCorporationIdBookmarksCoordinates;

    /**
     * created string
     */
    created: Date;

    /**
     * creator_id integer
     */
    creatorId: number;

    /**
     * folder_id integer
     */
    folderId?: number;

    item?: GetCorporationsCorporationIdBookmarksItem;

    /**
     * label string
     */
    label: string;

    /**
     * location_id integer
     */
    locationId: number;

    /**
     * notes string
     */
    notes: string;

}


