/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * jump_clone object
 */
export interface GetCharactersCharacterIdClonesJumpClone {
    /**
     * implants array
     */
    implants: Array<number>;

    /**
     * jump_clone_id integer
     */
    jumpCloneId: number;

    /**
     * location_id integer
     */
    locationId: number;

    /**
     * location_type string
     */
    locationType: GetCharactersCharacterIdClonesJumpClone.LocationTypeEnum;

    /**
     * name string
     */
    name?: string;

}
export namespace GetCharactersCharacterIdClonesJumpClone {
    export type LocationTypeEnum = 'station' | 'structure';
}


