/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * modifier object
 */
export interface GetDogmaEffectsEffectIdModifier {
    /**
     * domain string
     */
    domain?: string;

    /**
     * effect_id integer
     */
    effectId?: number;

    /**
     * func string
     */
    func: string;

    /**
     * modified_attribute_id integer
     */
    modifiedAttributeId?: number;

    /**
     * modifying_attribute_id integer
     */
    modifyingAttributeId?: number;

    /**
     * operator integer
     */
    operator?: number;

}


