/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * 200 ok object
 */
export interface GetFwSystems200Ok {
    /**
     * contested boolean
     */
    contested: boolean;

    /**
     * occupier_faction_id integer
     */
    occupierFactionId: number;

    /**
     * owner_faction_id integer
     */
    ownerFactionId: number;

    /**
     * solar_system_id integer
     */
    solarSystemId: number;

    /**
     * victory_points integer
     */
    victoryPoints: number;

    /**
     * victory_points_threshold integer
     */
    victoryPointsThreshold: number;

}


