/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * active_total object
 */
export interface GetFwLeaderboardsCharactersActiveTotal {
    /**
     * Amount of kills
     */
    amount?: number;

    /**
     * character_id integer
     */
    characterId?: number;

}


