/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * Summary of kills against an enemy faction for the given faction
 */
export interface GetFwStatsKills {
    /**
     * Last week's total number of kills against enemy factions
     */
    lastWeek: number;

    /**
     * Total number of kills against enemy factions since faction warfare began
     */
    total: number;

    /**
     * Yesterday's total number of kills against enemy factions
     */
    yesterday: number;

}


