/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * 200 ok object
 */
export interface GetIncursions200Ok {
    /**
     * The constellation id in which this incursion takes place
     */
    constellationId: number;

    /**
     * The attacking faction's id
     */
    factionId: number;

    /**
     * Whether the final encounter has boss or not
     */
    hasBoss: boolean;

    /**
     * A list of infested solar system ids that are a part of this incursion
     */
    infestedSolarSystems: Array<number>;

    /**
     * Influence of this incursion as a float from 0 to 1
     */
    influence: number;

    /**
     * Staging solar system for this incursion
     */
    stagingSolarSystemId: number;

    /**
     * The state of this incursion
     */
    state: GetIncursions200Ok.StateEnum;

    /**
     * The type of this incursion
     */
    type: string;

}
export namespace GetIncursions200Ok {
    export type StateEnum = 'withdrawing' | 'mobilizing' | 'established';
}


