/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GetLoyaltyStoresCorporationIdOffersRequiredItem } from './getLoyaltyStoresCorporationIdOffersRequiredItem';


/**
 * 200 ok object
 */
export interface GetLoyaltyStoresCorporationIdOffers200Ok {
    /**
     * isk_cost number
     */
    iskCost: number;

    /**
     * lp_cost integer
     */
    lpCost: number;

    /**
     * offer_id integer
     */
    offerId: number;

    /**
     * quantity integer
     */
    quantity: number;

    /**
     * required_items array
     */
    requiredItems: Array<GetLoyaltyStoresCorporationIdOffersRequiredItem>;

    /**
     * type_id integer
     */
    typeId: number;

}


