/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * 200 ok object
 */
export interface GetUniverseGroupsGroupIdOk {
    /**
     * category_id integer
     */
    categoryId: number;

    /**
     * group_id integer
     */
    groupId: number;

    /**
     * name string
     */
    name: string;

    /**
     * published boolean
     */
    published: boolean;

    /**
     * types array
     */
    types: Array<number>;

}


