/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * 200 ok object
 */
export interface GetUniverseFactions200Ok {
    /**
     * corporation_id integer
     */
    corporationId: number;

    /**
     * description string
     */
    description: string;

    /**
     * faction_id integer
     */
    factionId: number;

    /**
     * is_unique boolean
     */
    isUnique: boolean;

    /**
     * militia_corporation_id integer
     */
    militiaCorporationId?: number;

    /**
     * name string
     */
    name: string;

    /**
     * size_factor number
     */
    sizeFactor: number;

    /**
     * solar_system_id integer
     */
    solarSystemId: number;

    /**
     * station_count integer
     */
    stationCount: number;

    /**
     * station_system_count integer
     */
    stationSystemCount: number;

}


