/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * ally object
 */
export interface GetWarsWarIdAlly {
    /**
     * Alliance ID if and only if this ally is an alliance
     */
    allianceId?: number;

    /**
     * Corporation ID if and only if this ally is a corporation
     */
    corporationId?: number;

}


