/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * recipient object
 */
export interface PostCharactersCharacterIdMailRecipient {
    /**
     * recipient_id integer
     */
    recipientId: number;

    /**
     * recipient_type string
     */
    recipientType: PostCharactersCharacterIdMailRecipient.RecipientTypeEnum;

}
export namespace PostCharactersCharacterIdMailRecipient {
    export type RecipientTypeEnum = 'alliance' | 'character' | 'corporation' | 'mailing_list';
}


