/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * 200 ok object
 */
export interface PostUniverseNames200Ok {
    /**
     * category string
     */
    category: PostUniverseNames200Ok.CategoryEnum;

    /**
     * id integer
     */
    id: number;

    /**
     * name string
     */
    name: string;

}
export namespace PostUniverseNames200Ok {
    export type CategoryEnum = 'alliance' | 'character' | 'constellation' | 'corporation' | 'inventory_type' | 'region' | 'solar_system' | 'station';
}


