/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * new_settings object
 */
export interface PutFleetsFleetIdNewSettings {
    /**
     * Should free-move be enabled in the fleet
     */
    isFreeMove?: boolean;

    /**
     * New fleet MOTD in CCP flavoured HTML
     */
    motd?: string;

}


